import crypto from "node:crypto";

import { raw, serializeObjectLiteral } from "./codegen/serialize-object";
import type { MergedBetterAuthContribution } from "./contribution";

export function buildAuthFileSource(merged: MergedBetterAuthContribution): string {
  const lines: string[] = [
    'import { betterAuth } from "better-auth";',
    'import Database from "better-sqlite3";',
    ...merged.serverImports,
    "",
  ];
  if (merged.helperCode.length > 0) {
    lines.push(...merged.helperCode, "");
  }

  const configObject: Record<string, unknown> = {
    database: raw('new Database("./sqlite.db")'),
    ...merged.config,
  };
  if (merged.trustedOrigins.length > 0) {
    configObject.trustedOrigins = merged.trustedOrigins;
  }
  if (merged.pluginCalls.length > 0) {
    configObject.plugins = merged.pluginCalls.map((call) => raw(call));
  }

  lines.push(`export const auth = betterAuth(${serializeObjectLiteral(configObject)});`, "");
  return lines.join("\n");
}

export function buildAuthClientFileSource(merged: MergedBetterAuthContribution): string {
  const lines: string[] = [
    'import { createAuthClient } from "better-auth/react";',
    ...merged.clientImports,
    "",
  ];

  const configObject: Record<string, unknown> = {
    baseURL: raw("process.env.BETTER_AUTH_URL"),
  };
  if (merged.clientPluginCalls.length > 0) {
    configObject.plugins = merged.clientPluginCalls.map((call) => raw(call));
  }

  lines.push(
    `export const authClient = createAuthClient(${serializeObjectLiteral(configObject)});`,
    "",
  );
  return lines.join("\n");
}

/** Static regardless of which features are selected — `toNextJsHandler` covers everything. */
export const AUTH_ROUTE_SOURCE = [
  'import { auth } from "@/lib/auth";',
  'import { toNextJsHandler } from "better-auth/next-js";',
  "",
  "export const { POST, GET } = toNextJsHandler(auth);",
  "",
].join("\n");

export function generateBetterAuthSecret(): string {
  return crypto.randomBytes(32).toString("base64");
}

/**
 * `betterAuthSecret` is `undefined` for `.env.example` (committed safely, no real
 * secret) and a freshly-generated value for `.env` (gitignored, app works
 * immediately without the user having to run `openssl rand -base64 32` themselves).
 */
export function buildEnvFileContent(
  merged: MergedBetterAuthContribution,
  betterAuthSecret: string | undefined,
): string {
  const lines: string[] = [
    "# Generated by shell-cli (Better Auth)",
    `BETTER_AUTH_SECRET=${betterAuthSecret ?? ""}`,
    "BETTER_AUTH_URL=http://localhost:3000",
  ];
  for (const envVar of merged.envVars) {
    lines.push("");
    if (envVar.comment !== undefined) {
      lines.push(`# ${envVar.comment}`);
    }
    lines.push(`${envVar.key}=`);
  }
  return `${lines.join("\n")}\n`;
}
